In [1]:
 using Flux , Plots 

In [2]:
?σ


"σ" can be typed by \sigma<tab>

search: σ logσ hardσ



```
σ(x) = 1 / (1 + exp(-x))
```

Classic [sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function) activation function. Unicode `σ` can be entered as `\sigma` then tab, in many editors. The ascii name `sigmoid` is also exported.

See also [`sigmoid_fast`](@ref).

```
julia> using UnicodePlots

julia> lineplot(sigmoid, -5, 5, height=7)
          ┌────────────────────────────────────────┐     
        1 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⣀⡠⠤⠖⠒⠒⠋⠉⠉⠉⠉⠉⠉│ σ(x)
          │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⢀⡠⠖⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│     
          │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⣀⠔⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│     
   f(x)   │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⡏⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│     
          │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡔⠋⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│     
          │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠤⠊⠁⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│     
        0 │⣀⣀⣀⣀⣀⣀⣀⠤⠤⠤⠒⠊⠉⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│     
          └────────────────────────────────────────┘     
          ⠀-5⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀5⠀     
          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀x⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀     

julia> sigmoid === σ
true
```


In [3]:
model=Dense(2,1,σ)

Dense(2 => 1, σ)    # 3 parameters

In [4]:
@doc Dense

```
Dense(in => out, σ=identity; bias=true, init=glorot_uniform)
Dense(W::AbstractMatrix, [bias, σ])
```

Create a traditional fully connected layer, whose forward pass is given by:

```
y = σ.(W * x .+ bias)
```

The input `x` should be a vector of length `in`, or batch of vectors represented as an `in × N` matrix, or any array with `size(x,1) == in`. The out `y` will be a vector  of length `out`, or a batch with `size(y) == (out, size(x)[2:end]...)`

Keyword `bias=false` will switch off trainable bias for the layer. The initialisation of the weight matrix is `W = init(out, in)`, calling the function given to keyword `init`, with default [`glorot_uniform`](@ref Flux.glorot_uniform). The weight matrix and/or the bias vector (of length `out`) may also be provided explicitly.

# Examples

```jldoctest
julia> d = Dense(5 => 2)
Dense(5 => 2)       # 12 parameters

julia> d(rand(Float32, 5, 64)) |> size
(2, 64)

julia> d(rand(Float32, 5, 1, 1, 64)) |> size  # treated as three batch dimensions
(2, 1, 1, 64)

julia> d1 = Dense(ones(2, 5), false, tanh)  # using provided weight matrix
Dense(5 => 2, tanh; bias=false)  # 10 parameters

julia> d1(ones(5))
2-element Vector{Float64}:
 0.9999092042625951
 0.9999092042625951

julia> Flux.params(d1)  # no trainable bias
Params([[1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0]])
```


In [5]:
Flux.params(model)

Params([Float32[-1.1953473 -0.26885962], Float32[0.0]])

In [6]:
x=rand(2)
model(x)

1-element Vector{Float64}:
 0.4291549267517824

In [7]:
@doc methods 

```
methods(f, [types], [module])
```

Return the method table for `f`.

If `types` is specified, return an array of methods whose types match. If `module` is specified, return an array of methods defined in that module. A list of modules can also be specified as an array.

!!! compat "Julia 1.4"
    At least Julia 1.4 is required for specifying a module.


See also: [`which`](@ref) and `@which`.


In [8]:
@which methods 

Base

In [9]:
methods(Flux.mse)

# 1 method for generic function "mse":
[1] mse(ŷ, y; agg) in Flux.Losses at /home/suyash/.julia/packages/Flux/kq9Et/src/losses/functions.jl:45

In [13]:
using CSV,DataFrames


In [14]:
?CSV


search: CSV @colorant_str



CSV provides fast, flexible reader & writer for delimited text files in various formats.

Reading:

  * `CSV.File` reads delimited data and returns a `CSV.File` object, which allows dot-access to columns and iterating rows.
  * `CSV.read` is similar to `CSV.File` but used when the input will be passed directly to a sink function such as a `DataFrame`.
  * `CSV.Rows` reads delimited data and returns a `CSV.Rows` object, which allows "streaming" the data by iterating and thereby has a lower memory footprint than `CSV.File`.
  * `CSV.Chunks` allows processing extremely large files in "batches" or "chunks".

Writing:

  * `CSV.write` writes a [Tables.jl interface input](https://github.com/JuliaData/Tables.jl) such as a `DataFrame` to a csv file or an in-memory IOBuffer.
  * `CSV.RowWriter` creates an iterator that produces csv-formatted strings for each row in the input table.

Here is an example of reading a csv file and passing the input to a `DataFrame`:

```julia
using CSV, DataFrames
ExampleInputDF = CSV.read("ExampleInputFile.csv", DataFrame)
```

Here is an example of writing out a `DataFrame` to a csv file:

```julia
using CSV, DataFrames
ExampleOutputDF = DataFrame(rand(10,10), :auto)
CSV.write("ExampleOutputFile.csv", ExampleOutputDF)
```


In [35]:
apples=CSV.read("data/apples.dat", DataFrame, delim="\t")

492×5 DataFrame
 Row │ height    width    red       green     blue    
     │ Int64    Int64    Float64   Float64   Float64  
─────┼────────────────────────────────────────────────
   1 │      90       99  0.501466  0.229304  0.148436
   2 │      94       99  0.434225  0.128667  0.108166
   3 │      94       99  0.43412   0.128334  0.108348
   4 │      94       99  0.432922  0.127469  0.106358
   5 │      94       99  0.433292  0.126873  0.106027
   6 │      94       99  0.432438  0.127182  0.105781
   7 │      94       99  0.432922  0.127296  0.106408
   8 │      95       99  0.431167  0.126159  0.104195
   9 │      95       99  0.431867  0.125932  0.104244
  10 │      95       99  0.43034   0.126404  0.103801
  11 │      95       99  0.43023   0.125699  0.104274
  ⋮  │    ⋮        ⋮        ⋮         ⋮         ⋮
 483 │      98       99  0.460158  0.141178  0.110293
 484 │      98       99  0.461967  0.142167  0.111156
 485 │      98       99  0.462939  0.144067  0.11163
 486 │      99       99  0.464322  0.143808  0.111625
 487 │      99       99  0.465106  0.14517   0.111227
 488 │      98       99  0.467485  0.146692  0.113257
 489 │      98       99  0.468352  0.147962  0.112711
 490 │      98       99  0.471226  0.150144  0.113324
 491 │      99       99  0.52215   0.199051  0.1244
 492 │      98       99  0.471621  0.150672  0.113324
                                      471 rows omitted

In [36]:
bananas=CSV.read("data/Banana.dat",DataFrame,delim="\t")

490×5 DataFrame
 Row │ height    width    red       green     blue    
     │ Int64    Int64    Float64   Float64   Float64  
─────┼────────────────────────────────────────────────
   1 │      98       99  0.583507  0.500662  0.207504
   2 │      50       99  0.609666  0.514869  0.186871
   3 │      52       99  0.610012  0.515759  0.187504
   4 │      99       69  0.568033  0.492939  0.239316
   5 │      51       99  0.609766  0.51485   0.183329
   6 │      53       99  0.608089  0.514609  0.183374
   7 │      53       99  0.608676  0.515487  0.186206
   8 │      53       99  0.609278  0.516486  0.188582
   9 │      99       67  0.569099  0.494501  0.241941
  10 │      54       99  0.610284  0.516183  0.189116
  11 │      54       99  0.607329  0.515344  0.188351
  ⋮  │    ⋮        ⋮        ⋮         ⋮         ⋮
 481 │      37       99  0.524028  0.452379  0.226256
 482 │      37       99  0.523906  0.452571  0.230475
 483 │      39       99  0.523823  0.4514    0.229759
 484 │      39       99  0.522489  0.449973  0.233683
 485 │      41       99  0.517573  0.444391  0.227029
 486 │      41       99  0.515956  0.441912  0.230229
 487 │      41       99  0.517585  0.444827  0.234798
 488 │      41       99  0.510357  0.436022  0.228139
 489 │      43       99  0.508873  0.43433   0.230683
 490 │      31       99  0.528205  0.440139  0.199588
                                      469 rows omitted

In [40]:
size(apples)[1]

492

In [81]:
x_apples=[[row." red ",row." green "] for row in eachrow(apples)]

492-element Vector{Vector{Float64}}:
 [0.5014661151631883, 0.22930441097534052]
 [0.4342254940829249, 0.1286670449863579]
 [0.4341196192611507, 0.1283343194344977]
 [0.43292152183068955, 0.12746865916878627]
 [0.4332916920418286, 0.12687320747253036]
 [0.43243837386176553, 0.12718165906107473]
 [0.4329222095428659, 0.127296222767609]
 [0.4311669294311532, 0.12615909751878962]
 [0.43186658074810524, 0.12593155154602345]
 [0.4303403153394724, 0.12640444560215408]
 [0.4302302502007849, 0.12569890987963223]
 [0.4850330408406459, 0.20774997291734418]
 [0.4289987119309, 0.12556138558335778]
 ⋮
 [0.4567426454785655, 0.13869407466403796]
 [0.4590486162219305, 0.1395517990505897]
 [0.4601581872919335, 0.14117849279714548]
 [0.46196735818763357, 0.1421665971353089]
 [0.4629390550656122, 0.1440671374165337]
 [0.46432223450752835, 0.14380783472718045]
 [0.46510595158618334, 0.1451697450733138]
 [0.4674854279681992, 0.14669161842995918]
 [0.4683520273050642, 0.1479623444588349]
 [0.4712256099559536

In [82]:
x_bananas=[[row." red ",row." green "] for row in eachrow(bananas)]

490-element Vector{Vector{Float64}}:
 [0.5835067538126356, 0.500662309368192]
 [0.6096658836445241, 0.514868541076373]
 [0.61001222127424, 0.5157592947018083]
 [0.5680333392636676, 0.4929391278094967]
 [0.6097662880271572, 0.5148498882514222]
 [0.6080886893475433, 0.5146088965412025]
 [0.6086763977507786, 0.5154866998805462]
 [0.6092775365179625, 0.5164860873506747]
 [0.5690986557452848, 0.4945007761667278]
 [0.610284435646972, 0.5161825666623635]
 [0.607329117213896, 0.5153440757746397]
 [0.6083665640474657, 0.5146497517166334]
 [0.6063312071816673, 0.5137782965773128]
 ⋮
 [0.5291302161890399, 0.4403100385453329]
 [0.5287307644576823, 0.4565478406552493]
 [0.5240277326400172, 0.45237940480059413]
 [0.5239057876671794, 0.4525711129522229]
 [0.5238233433790978, 0.45140008185437314]
 [0.5224889335097888, 0.44997337957681116]
 [0.5175726263709806, 0.4443909309164674]
 [0.5159556048834634, 0.4419119496855347]
 [0.5175850178187539, 0.44482679017155075]
 [0.5103568171454631, 0.43602228682170

In [83]:
xs=[x_apples;x_bananas]

982-element Vector{Vector{Float64}}:
 [0.5014661151631883, 0.22930441097534052]
 [0.4342254940829249, 0.1286670449863579]
 [0.4341196192611507, 0.1283343194344977]
 [0.43292152183068955, 0.12746865916878627]
 [0.4332916920418286, 0.12687320747253036]
 [0.43243837386176553, 0.12718165906107473]
 [0.4329222095428659, 0.127296222767609]
 [0.4311669294311532, 0.12615909751878962]
 [0.43186658074810524, 0.12593155154602345]
 [0.4303403153394724, 0.12640444560215408]
 [0.4302302502007849, 0.12569890987963223]
 [0.4850330408406459, 0.20774997291734418]
 [0.4289987119309, 0.12556138558335778]
 ⋮
 [0.5291302161890399, 0.4403100385453329]
 [0.5287307644576823, 0.4565478406552493]
 [0.5240277326400172, 0.45237940480059413]
 [0.5239057876671794, 0.4525711129522229]
 [0.5238233433790978, 0.45140008185437314]
 [0.5224889335097888, 0.44997337957681116]
 [0.5175726263709806, 0.4443909309164674]
 [0.5159556048834634, 0.4419119496855347]
 [0.5175850178187539, 0.44482679017155075]
 [0.5103568171454631, 0

In [84]:
ys=[fill(0,size(x_apples));fill(1,size(x_bananas))]

982-element Vector{Int64}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [85]:
model = Dense(2,1,σ)

Dense(2 => 1, σ)    # 3 parameters

In [88]:
model(xs[end])

1-element Vector{Float64}:
 0.545343982427747

In [92]:
loss=Flux.mse(model(xs[1]),ys[1])

0.2887512152074748

In [94]:
typeof(loss)

Float64

In [95]:
using Flux.Tracker 
back!(loss)

LoadError: UndefVarError: Tracker not defined